### ISSUE TITLE
Review: Architecture Documentation

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Hackaton-Team-5#9]
Please read and review the [Architecture Documentation](https://github.com/cs-utulsa/Hackaton-Team-5/wiki/Backend-Architecture) for the backend classes. Need to make sure we all agree on this functionally and are going to build it. Please comment on this issue once you have read it and are ok with it.

- [x] Josh
- [x] Keely
- [x] Dawson
- [x] Eliga

**Comment by dawsonjones2020** [comment]
I think it's fine. I can code the student and event classes pretty easily so I'll get started on that
